# Generated by Django 5.0.2 on 2024-03-03 15:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainApp', '0002_mijoz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sotuv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.PositiveSmallIntegerField()),
                ('summa', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('tolandi', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('qarz', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('sana', models.DateField()),
                ('mahsulot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.mahsulot')),
                ('mijoz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.mijoz')),
            ],
        ),
    ]
