# Generated by Django 5.0.2 on 2024-03-04 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_mijoz'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='narx2',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
