# Generated by Django 5.0.2 on 2024-03-04 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_mahsulot_narx2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahsulot',
            name='narx2',
        ),
    ]
